name: ci

on:
  push:
    branches: master
    
    env:
    DOTNET_VERSION: '5.0.x'
    AZURE_WEBAPP_NAME: restaurantxpress 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
       - name: Checkout
         uses: actions/checkout@v2
      
       - name: Setup .NET 5
         uses: actions/setup-dotnet@v1
         with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
       - name: Start SQL Server
         run: |
           docker run -d -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Pass~w0r8" -e "MSSQL_PID=Express" -p 1433:1433 -d mcr.microsoft.com/mssql/server:latest
           
       - name: Sleep for 5 seconds
         uses: jakejarvis/wait-action@master
         with:
           time: '5s'

       - name: Restore dependencies
         run: dotnet restore
      
       - name: Build app
         run: dotnet build -c Release --no-restore
         
       - name: Run automated tests
         env:
           ConnectionStrings__DefaultConnection: data source=localhost;Database=RestauDB_Test;User=sa;Password=Pass~w0r8
         run: dotnet test -c Release --no-build
         
       - name: Publish app
         run: dotnet publish -c Release -o ./out
         
       - name: Deploy to Azure Web Apps
         uses: azure/webapps-deploy@v2
         with:
           app-name: ${{ env.AZURE_WEBAPP_NAME }}
           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_SECRET }}
           package: ./out
      